#!/usr/bin/env bash

# Give the container time to spin up
printf 'Waiting for web container to start up'
until $(curl --output /dev/null --silent --head http://localhost:3000); do
    printf '.'
    sleep 1
done

echo ' ready'

[ $(curl -sL -w "%{http_code}" http://localhost:3000/ -o /dev/null) -eq 200 ] || exit 1
